- hosts: my_vm
  become: yes
  tasks:
    - name: Pull MySQL Docker image
      community.docker.docker_image:
        name: mysql
        tag: latest
        source: pull

    - name: Run MySQL container for Muqadas
      community.docker.docker_container:
        name: mysql-server-muqadas
        image: mysql:latest
        state: started
        env:
          MYSQL_ROOT_PASSWORD: "muqadas_root_password"
          MYSQL_DATABASE: "muqadas_zabbix"
          MYSQL_USER: "muqadas_zabbix"
          MYSQL_PASSWORD: "muqadas_zabbix"
        ports:
          - "3308:3306"

    - name: Pull Zabbix Docker image
      community.docker.docker_image:
        name: zabbix/zabbix-server-mysql
        tag: latest
        source: pull

    - name: Run Zabbix container for Muqadas
      community.docker.docker_container:
        name: zabbix-muqadas
        image: zabbix/zabbix-server-mysql:latest
        state: started
        ports:
          - "8084:80"
          - "10054:10051"
        env:
          DB_SERVER_HOST: "mysql-server-muqadas"
          MYSQL_USER: "muqadas_zabbix"
          MYSQL_PASSWORD: "muqadas_zabbix"
          MYSQL_DATABASE: "muqadas_zabbix"

    - name: Pull Nagios Docker image
      community.docker.docker_image:
        name: jasonrivers/nagios
        tag: latest
        source: pull

    - name: Run Nagios container for Muqadas
      community.docker.docker_container:
        name: nagios-muqadas
        image: jasonrivers/nagios:latest
        state: started
        ports:
          - "8085:80"

    - name: Pull Prometheus Docker image
      community.docker.docker_image:
        name: prom/prometheus
        tag: v2.30.3
        source: pull

    - name: Run Prometheus container for Muqadas
      community.docker.docker_container:
        name: prometheus-muqadas
        image: prom/prometheus:v2.30.3
        state: started
        ports:
          - "8086:9090"
